/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.seguradora.view;

import java.sql.*;
import javax.swing.JOptionPane;
import br.com.seguradora.util.ModuloConexao;

/**
 *
 * @author weslleyjoaquim
 */
public class TelaAutomovel extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAutomovel
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public TelaAutomovel() {
        initComponents();
        conexao = ModuloConexao.conector();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRenavam = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        lblAnoDeFabricacao = new javax.swing.JLabel();
        lblAnoDoCarro = new javax.swing.JLabel();
        textRenavam = new javax.swing.JTextField();
        textFabricante = new javax.swing.JTextField();
        textPlaca = new javax.swing.JTextField();
        textModelo = new javax.swing.JTextField();
        textAnoCarro = new com.toedter.calendar.JYearChooser();
        textAnoFabricacao = new com.toedter.calendar.JYearChooser();
        btnAddAutomovel = new javax.swing.JButton();
        btnConsultaAutomovel = new javax.swing.JButton();
        btnEditAutomovel = new javax.swing.JButton();
        btnDeleteAutomovel = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Automóveis");

        lblRenavam.setText("RENAVAM:");

        lblPlaca.setText("Placa:");

        lblModelo.setText("Modelo:");

        lblFabricante.setText("Fabricante:");

        lblAnoDeFabricacao.setText("Ano de Fabricação:");

        lblAnoDoCarro.setText("Ano do Carro:");

        textRenavam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRenavamActionPerformed(evt);
            }
        });

        textFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFabricanteActionPerformed(evt);
            }
        });

        textPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPlacaActionPerformed(evt);
            }
        });

        textModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textModeloActionPerformed(evt);
            }
        });

        btnAddAutomovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/view/IMAGE/userAdicionar.png"))); // NOI18N
        btnAddAutomovel.setToolTipText("");
        btnAddAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAutomovelActionPerformed(evt);
            }
        });

        btnConsultaAutomovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/view/IMAGE/userPesquisar.png"))); // NOI18N
        btnConsultaAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaAutomovelActionPerformed(evt);
            }
        });

        btnEditAutomovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/view/userEditar.png"))); // NOI18N
        btnEditAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAutomovelActionPerformed(evt);
            }
        });

        btnDeleteAutomovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/view/userDeletar.png"))); // NOI18N
        btnDeleteAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAutomovelActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/view/impressora.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddAutomovel)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultaAutomovel)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditAutomovel)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAutomovel)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAnoDoCarro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAnoDeFabricacao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblRenavam)
                    .addComponent(lblPlaca)
                    .addComponent(lblFabricante)
                    .addComponent(lblModelo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textRenavam, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(textPlaca)
                            .addComponent(textFabricante)
                            .addComponent(textModelo))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRenavam)
                    .addComponent(textRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(textPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFabricante)
                    .addComponent(textFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAnoDoCarro)
                    .addComponent(textAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnoDeFabricacao))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAutomovel)
                    .addComponent(btnConsultaAutomovel)
                    .addComponent(btnEditAutomovel)
                    .addComponent(btnDeleteAutomovel)
                    .addComponent(jButton5))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setBounds(0, 0, 518, 393);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        
        String sql = "insert into automovel(renavam, placa, fabricante, modelo,anomodelo, anofabricacao)"
                + "values(?,?,?,?,?,?)";
        
       try{
            pst = conexao.prepareStatement(sql);
       
            pst.setString(1,textRenavam.getText());
            pst.setString(2,textPlaca.getText());
            pst.setString(3,textFabricante.getText());
            pst.setString(4,textModelo.getText());
            pst.setInt(5,textAnoCarro.getYear());
            pst.setInt(6,textAnoFabricacao.getYear());

            int resultado = pst.executeUpdate();
            System.out.println(pst);
            if(resultado==1){
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
                    textRenavam.setText(null);
                    textPlaca.setText(null);
                    textFabricante.setText(null);
                    textModelo.setText(null);
                    textAnoCarro.setYear(2023);
                    textAnoFabricacao.setYear(2023);
                    
            
            }else
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }
    
    //Metodo consultar
    private void consultar(){
        String sql = "select*from automovel where renavam=?";
        try{
            pst=conexao.prepareStatement(sql);
            pst.setString(1, textRenavam.getText());

            rs = pst.executeQuery();
            if(rs.next()){

                    textPlaca.setText(rs.getString("placa"));
                    textFabricante.setText(rs.getString("fabricante"));
                    textModelo.setText(rs.getString("modelo"));
                    textAnoCarro.setYear(rs.getInt("anomodelo"));
                    textAnoFabricacao.setYear(rs.getInt("anofabricacao"));
            }else{
                JOptionPane.showMessageDialog(null, "Automóvel não encontrado");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //Metodo para atualizar cadastrado
    
    private void atualizar(){
        String sql = "update automovel set placa=?, fabricante=?, modelo=?,anomodelo=?,"
                + "anofabricacao=? where renavam=?";
        
        try{
            pst = conexao.prepareStatement(sql);
            
            pst.setString(6,textRenavam.getText());
            pst.setString(1,textPlaca.getText());
            pst.setString(2,textFabricante.getText());
            pst.setString(3,textModelo.getText());
            pst.setInt(4,textAnoCarro.getYear());
            pst.setInt(5,textAnoFabricacao.getYear());
            
            System.out.println(pst);
            int atualizado = pst.executeUpdate();

            if (atualizado == 1) {
                JOptionPane.showMessageDialog(null, "Automóvel atualizado com sucesso!");
                
                textRenavam.setText(null);
                textPlaca.setText(null);
                textFabricante.setText(null);
                textModelo.setText(null);
                textAnoCarro.setYear(2023);
                textAnoFabricacao.setYear(2023);
            }else{
                JOptionPane.showMessageDialog(null, "Automóvel não encontrado");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //Metodo para deletar autmóvel
    
    private void remover() {

        int confirma = JOptionPane.showConfirmDialog(null, "Deseja  remover ?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_NO_OPTION) {
            String sql = "delete from automovel where renavam=?";

            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, textRenavam.getText());
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Automóvel removido com sucesso!!!!");
                textRenavam.setText(null);
                textPlaca.setText(null);
                textFabricante.setText(null);
                textModelo.setText(null);
                textAnoCarro.setYear(2023);
                textAnoFabricacao.setYear(2023);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }
    private void textRenavamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRenavamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRenavamActionPerformed

    private void textFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFabricanteActionPerformed

    private void textPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPlacaActionPerformed

    private void textModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textModeloActionPerformed

    private void btnAddAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAutomovelActionPerformed
        // TODO add your handling code here:
        cadastrar();
    }//GEN-LAST:event_btnAddAutomovelActionPerformed

    private void btnConsultaAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaAutomovelActionPerformed
        // TODO add your handling code here:
        consultar();
    }//GEN-LAST:event_btnConsultaAutomovelActionPerformed

    private void btnEditAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAutomovelActionPerformed
        // TODO add your handling code here:
        atualizar();
    }//GEN-LAST:event_btnEditAutomovelActionPerformed

    private void btnDeleteAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAutomovelActionPerformed
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_btnDeleteAutomovelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAutomovel;
    private javax.swing.JButton btnConsultaAutomovel;
    private javax.swing.JButton btnDeleteAutomovel;
    private javax.swing.JButton btnEditAutomovel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel lblAnoDeFabricacao;
    private javax.swing.JLabel lblAnoDoCarro;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblRenavam;
    private com.toedter.calendar.JYearChooser textAnoCarro;
    private com.toedter.calendar.JYearChooser textAnoFabricacao;
    private javax.swing.JTextField textFabricante;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textPlaca;
    private javax.swing.JTextField textRenavam;
    // End of variables declaration//GEN-END:variables
}
